import { expect, test } from '@playwright/test'

test('guest can use the advisor without sign-in and history remains disabled', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: /Continue without signing in/i }).click()
  await expect(page.getByText(/Guest conversation · not saved/i)).toBeVisible()
  await page.getByPlaceholder(/Ask an academic question/i).fill('What are prerequisites for CSC-211?')
  await page.getByRole('button', { name: 'Send query' }).click()
  await expect(page.getByText(/PROGRESSION GUIDANCE - inferred from the official Fall 2025 semester sequence/i)).toBeVisible()
  await expect(page.getByRole('button', { name: 'History' })).toHaveCount(0)
  await expect(page.getByText(/Sign in to save and revisit/i)).toBeVisible()
  await page.getByRole('button', { name: 'Fees', exact: true }).click()
  await expect(page.getByText('BS Computer Science fee structure')).toBeVisible()
  await expect(page.getByText('PKR 106,530')).toBeVisible()
  await expect(page.getByRole('link', { name: /official QAU fee page/i })).toBeVisible()
  await page.getByRole('button', { name: 'Study Plan', exact: true }).click()
  await expect(page.getByText('BSCS eight-semester study plan')).toBeVisible()
  await expect(page.getByText('Semester 8')).toBeVisible()
  await expect(page.getByText(/Six to eight weeks during the degree/i)).toBeVisible()
  await page.screenshot({ path: 'test-results/study-plan.png', fullPage: true })
})

test('student registers, asks a bilingual-ready academic query, and sees saved history', async ({ page }) => {
  const email = `e2e-${Date.now()}@students.qau.edu.pk`
  await page.goto('/')
  await expect(page.getByText('Sign in to your advisor')).toBeVisible()
  await page.getByRole('button', { name: /Create an account/i }).click()
  await page.getByLabel('Full name').fill('E2E Student')
  await page.getByLabel('Email').fill(email)
  await page.getByLabel('Password', { exact: true }).fill('SecurePass123!')
  await page.getByLabel('Confirm password').fill('SecurePass123!')
  await page.getByRole('button', { name: 'Register', exact: true }).click()

  await expect(page.getByText('Mixed knowledge base')).toBeVisible()
  await expect(page.getByRole('button', { name: 'اردو' })).toBeVisible()
  await page.getByPlaceholder(/Ask an academic question/i).fill('What are prerequisites for CSC-211?')
  await page.getByRole('button', { name: 'Send query' }).click()
  await expect(page.getByText(/PROGRESSION GUIDANCE - inferred from the official Fall 2025 semester sequence/i)).toBeVisible()

  await page.getByRole('button', { name: /Timetable/ }).click()
  await page.getByRole('button', { name: 'View timetable' }).click()
  await expect(page.getByText(/synthetic timetable/i)).toBeVisible()
  await expect(page.getByText('CSC-211').first()).toBeVisible()

  await page.getByRole('button', { name: /History/ }).click()
  await expect(page.getByText('What are prerequisites for CSC-211?')).toBeVisible()
  await page.screenshot({ path: 'test-results/student-history.png', fullPage: true })
})

test('administrator signs in and can open protected management modules', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Email').fill('admin@cs.qau.edu.pk')
  await page.getByLabel('Password').fill('ChangeMeAdmin123!')
  await page.getByRole('button', { name: 'Sign in', exact: true }).click()
  await expect(page.getByText(/Admin control centre/i)).toBeVisible()
  await page.getByRole('button', { name: /Query Logs/ }).first().click()
  await expect(page.getByText('Search and export query logs')).toBeVisible()
  await page.getByRole('button', { name: /Reports/ }).first().click()
  await expect(page.getByText('Generate report')).toBeVisible()
})
